name: Test (PyPI)

on:
  push:
    branches:
      - pypi
  schedule:
    - cron: "0 18 * * 1,3,5"

jobs:
  test:
    name: Test PyPI (${{ matrix.os }}, py${{ matrix.python-version }}, tf${{ matrix.tensorflow }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        os: [ubuntu-20.04, windows-latest, macos-latest] # macos-latest is arm64-based
        python-version: ['3.9', '3.10', '3.11', '3.12']
        tensorflow: [2]
        include:
          # always set 'package-extras' for testing
          - tensorflow: 2
            package-extras: 'test'
          # add extra run to test latest tensorflow with legacy keras
          - os: ubuntu-20.04
            python-version: '>=3.12 <3.13'  # intentionally be different than '3.12' to cause an additional combination
            tensorflow: 2
            package-extras: 'test'
            deps-extra: 'tf_keras'
            exec-extra: 'echo "TF_USE_LEGACY_KERAS=1" >> $GITHUB_ENV'
          - os: macos-13
            python-version: '>=3.12 <3.13'  # intentionally be different than '3.12' to cause an additional combination
            tensorflow: 2
            package-extras: 'test'

    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip, wheel, setuptools
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install TensorFlow
        run: pip install "tensorflow==${{ matrix.tensorflow }}.*"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install extra dependencies (if any)
        if: ${{ matrix.deps-extra }}
        run: pip install ${{ matrix.deps-extra }}

      - name: Install package from source (just to test wheel building) - Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: pip install --no-binary stardist "stardist[${{ matrix.package-extras }}]"

      - name: Install package from source (just to test wheel building) - Windows
        if: startsWith(matrix.os, 'windows')
        run: pip install --no-binary stardist "stardist[${{ matrix.package-extras }}]"
        env:  # cf. https://github.com/pypa/pip/issues/11231
          TEMP: "/tmp"    # notes:
          TMPDIR: "/tmp"  # - /tmp should already exist on runner image
          TMP: "/tmp"     # - set all temp-related env variables (had issues with when omitting some)

      # - name: Install package from source (just to test wheel building) - macOS
      #   if: startsWith(matrix.os, 'macos')
      #   run: ...

      - name: Install package from wheel
        shell: bash
        run: |
          [[ -z $(pip list | grep stardist) ]] || pip uninstall -y stardist
          pip install --no-cache-dir --only-binary stardist "stardist[${{ matrix.package-extras }}]>0"

      - name: Run extra commands (if any)
        if: ${{ matrix.exec-extra }}
        run: ${{ matrix.exec-extra }}
        shell: bash

      - name: Disable PytestReturnNotNoneWarning
        run: echo "PYTEST_ADDOPTS='-W ignore::pytest.PytestReturnNotNoneWarning'" >> $GITHUB_ENV
        shell: bash

      - name: Run tests
        run: pytest -m "not gpu"
